# Generated by Django 6.0.5 on 2026-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='participation_type',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('volunteer', 'Volunteer')], default='attendee', max_length=20),
        ),
    ]
