# Generated by Django 6.0.6 on 2026-06-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('background', models.CharField(help_text='e.g. B.Tech Computer Science, Class of 2014', max_length=250)),
                ('experience', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
